import express from 'express';
import user from './userRoutes';
import items from './itemRoutes';
import supplier from './supplierRoutes';
import order from './orderRoutes';
import category from './categoryRoutes';
import proforma from './proformaRoutes';
import search from './search';
import users from './users';
import news from './news';
import authentications from './authentications';
import events from './events';
import comments from './comment';
import members from './members';
import notification from './conversations';
import messages from './messages';
import replies from './replies';
import contact from './contact';
import publications from './publications';
import maillists from './maillists';
import requestevent from './formrequestevent';
import tours from './tours';
import requesttravel from './requesttravel';
import participant from './participants';
import payments from './payment.route';

const router = express.Router();

router.use('/users', users);
router.use('/news', news);
router.use('/events', events);
router.use('/auth', authentications);
router.use('/comments', comments);
router.use('/members', members);
router.use('/notification', notification);
router.use('/messages', messages);
router.use('/replies', replies);
router.use('/contact', contact);
router.use('/publications', publications);
router.use('/maillist', maillists);
router.use('/supplier', supplier);
router.use('/user', user);
router.use('/item', items);
router.use('/order', order);
router.use('/category', category);
router.use('/proforma', proforma);
router.use('/search', search);
router.use('/requestevent', requestevent);
router.use('/tours', tours);
router.use('/requesttravel', requesttravel);
router.use('/participant', participant);
router.use('/payments', payments);

export default router;
